<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo picescape(APP_NAME); ?> - Album Viewer</title>
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "bootstrap.min.css"); ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "fontawesome.css"); ?>" media="all">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.css" integrity="sha256-d0mtrHsQZQe2+DIl6Z+F1rVWLI++ycF3BEXQUWf04xs=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.mobile.css" integrity="sha256-jXmPL1Q5E9IDaGmoKFLCbahYWC8zrPDwq8oNBQlzoyM=" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "galleria-themes/galleria.classicmod.css"); ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "styles.css"); ?>" media="all">
</head>

<body>

<div id="content" class="container">
<h1><?php echo picescape(APP_NAME); ?></h1>
<h2>Album Viewer</h2>

<div class="row">
    <div id="albums" class="col-xs-12 col-md-6">
        <div class="form-group">
            <label for="albums-select">Albums</label>
            <div class="input-group">
                <select id="albums-select" class="form-control">
                <option value=""></option>
                </select>
            </div>
        </div>
    </div>
</div>

<div id="album-gallery" style="display:none;">
<div class="row">
    <div class="col-xs-12">
        <div data-gallery-container></div>
        <div class="visible-xs" style="margin-top: 10px;">
            <button type="button" data-gallery-fullscreen-activate class="btn btn-primary btn-block">Fullscreen</button>
        </div>
    </div>
</div>
</div>

</div>

<div id="footer">
<div class="container">
<small>This site runs Pictorials v<?php echo VERSION; ?></small>
<small class="pull-right"><a href="<?php echo scriptUrl(""); ?>">Home</a></small>
</div>
</div>

<div style="display:none;">
<script type="application/json" id="ajax-urls">
{
    "download": "<?php echo scriptUrl("loadimage"); ?>",
    "getalbumdetails": "<?php echo scriptUrl("albumdetails", array("access_mode" => "view_album")); ?>",
    "getalbumsortedfiles": "<?php echo scriptUrl("albumfiles", array("access_mode" => "view_album")); ?>",
    "sysload": "<?php echo scriptUrl("sysload"); ?>"
}
</script>

<script type="application/json" id="image-urls">
{
    "dummy": "<?php echo assetUrl("img", "cross.svg"); ?>"
}
</script>
</div>

<div style="display:none;">
<script type="text/x-html-template" id="image-layer-template">
<div class="galleria-pictorials-layer-container">
<div class="galleria-pictorials-layer">
    @{if title}<h4>#{title}</h4>@{endif}
    @{if description}<p>#{description}</p>@{endif}
    @{if author}<p>Author: #{author}</p>@{endif}
    @{if people}<p>People: #{people|csv}</p>@{endif}
    @{if tags}<p>Tags: #{tags|csv}</p>@{endif}
</div>
</div>
</script>
</div>

<div style="display:none;">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/jquery-ajax-native.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/bootstrap.min.js"); ?>"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.js" integrity="sha256-Wdie7xDu6PuVG6BqNy/dEEYY0jK2JutDYnn0sI19yTw=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.mobile.js" integrity="sha256-84wtYJTPHtuXdY+6x/khPD5SruMKvYOUsJcYPNJ9dvk=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/galleria/1.5.7/galleria.min.js" integrity="sha256-vcRq33WsCAofqsEfm42WcAdAjyj8Q+XnuAnvg8ZuMLk=" crossorigin="anonymous"></script>

<script type="text/javascript" src="<?php echo assetUrl("js", "lazyload.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "notification-manager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "escaper.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "templater.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "sysload-checker.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "concurrency-manager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "progressive-file-loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "albums.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "galleria-loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "album-gallery.js"); ?>"></script>

<script type="text/javascript" src="<?php echo templateUrl("albumviewer"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "album-viewer.js"); ?>"></script>

<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/galleria.classicmod.js"); ?>"></script>
</div>

</body>
</html>
