<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo htmlspecialchars(APP_NAME); ?> - Album Manager</title>
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "bootstrap.min.css"); ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "styles.css"); ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "fontawesome.css"); ?>" media="all">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.css" integrity="sha256-d0mtrHsQZQe2+DIl6Z+F1rVWLI++ycF3BEXQUWf04xs=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.mobile.css" integrity="sha256-jXmPL1Q5E9IDaGmoKFLCbahYWC8zrPDwq8oNBQlzoyM=" crossorigin="anonymous" />
</head>

<body>

<div id="content" class="container">
<h1><?php echo htmlspecialchars(APP_NAME); ?></h1>
<h2>Album Manager</h2>

<div class="row">
    <div id="albums" class="col-xs-12 col-md-6">
        <div class="form-group">
            <label for="albums-select">Albums</label>
            <select id="albums-select" class="form-control">
            <option value=""></option>
            <?php foreach ($albums as $albumID => $albumName): ?>
            <option value="<?php echo $albumID; ?>"><?php echo htmlspecialchars($albumName); ?></option>
            <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div id="global-toolbar" class="col-xs-12 col-md-6">
        <div class="dropdown hidden-xs hidden-sm">
            <button type="button" id="actions-menu" class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Actions
                <span class="caret"></span>
            </button>
            <div class="dropdown-menu pull-right" role="menu" aria-labelledby="actions-menu">
                <button type="button" data-album-creator-activate class="btn btn-link btn-block">Create Album</button>
            </div>
        </div>
        <div class="visible-xs visible-sm">
            <button type="button" id="actions-list" class="btn btn-link" data-toggle="visible-state" data-target="global-toolbar-mobile" aria-expanded="false">
                Actions
                <span class="caret"></span>
            </button>
            <ul id="global-toolbar-mobile" class="list-inline" data-visible-state="closed" role="menu" aria-labelledby="actions-list">
                <li><button type="button" data-album-creator-activate class="btn btn-block">Create Album</button></li>
            </ul>
        </div>
    </div>
</div>

<br>

<div class="row">
    <div class="col-xs-12">
    </div>
</div>

</div>

<div id="footer">
<div class="container">
<small>This site runs Pictorials v<?php echo VERSION; ?></small>
</div>
</div>

<div id="loader" style="display:none;">
    <img src="<?php echo assetUrl("img", "spinner.svg"); ?>" alt="Loading" class="loader-img fa-pulse" data-loader-indicator>
    <div class="progress" data-loader-progress style="display:none;">
        <div data-progress-bar class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">&nbsp;</div>
    </div>
</div>

<div style="display:none;">

<script type="application/json" id="paths">
<?php echo json_encode($paths); ?>
</script>

<script type="application/json" id="ajax-urls">
{
    "createalbum": "<?php echo scriptUrl("albummanager", array("action" => "create")); ?>",
    "editalbum": "<?php echo scriptUrl("albummanager", array("action" => "edit")); ?>"
}
</script>

</div>

<div style="display:none;">
<script type="text/x-html-template" id="album-edit-form-template">
<div class="flip">
<div class="card">
    <div class="face front">
        <div class="well well-sm inner">
            <h3>#{name}</h3>
            <div class="table-responsive">
                <table class="table table-striped">
                    <tbody>
                    <tr>
                        <th>Path</th>
                        <td>#{path_name}</td>
                    </tr>
                    <tr>
                        <th>Picture Count</th>
                        <td>#{picture_count}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="face back">
        <div class="well well-sm inner">
            <h3>Edit</h3>
            <form data-album-edit-form>
                <div class="form-group">
                    <label for="album-edit-name">Name</label>
                    <input type="text" id="album-edit-name" class="form-control" value="${name}">
                </div>
                <button type="submit" class="btn btn-default">Save</button>
            </form>
        </div>
    </div>
</div>
</div>
</script>
</div>

<div style="display:none;">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/bootstrap.min.js"); ?>"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.js" integrity="sha256-Wdie7xDu6PuVG6BqNy/dEEYY0jK2JutDYnn0sI19yTw=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.mobile.js" integrity="sha256-84wtYJTPHtuXdY+6x/khPD5SruMKvYOUsJcYPNJ9dvk=" crossorigin="anonymous"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/bootbox-dev-4.4.1.js"); ?>"></script>

<script type="text/javascript" src="<?php echo assetUrl("js", "modal-manager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "bootbox.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "notification-manager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "albums.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "album-creator.js"); ?>"></script>

<script type="text/javascript" src="<?php echo templateUrl("albummanager"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "album-manager.js"); ?>"></script>
</div>

</body>
</html>
