<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo picescape(APP_NAME); ?> - File Browser</title>
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "bootstrap.min.css"); ?>" media="all">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" media="all" integrity="sha256-jySGIHdxeqZZvJ9SHgPNjbsBP8roij7/WjgkoGTJICk=" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "styles.css"); ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "fontawesome.css"); ?>" media="all">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.css" integrity="sha256-d0mtrHsQZQe2+DIl6Z+F1rVWLI++ycF3BEXQUWf04xs=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.mobile.css" integrity="sha256-jXmPL1Q5E9IDaGmoKFLCbahYWC8zrPDwq8oNBQlzoyM=" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.css" media="all" integrity="sha256-bOWY8F32FGGbNDMPAnwWl/Lv9CKen4IQsNZ4RU9rcs0=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js-bootstrap-css/1.2.1/typeaheadjs.min.css" integrity="sha256-ASp4bvLQ21NxBA4wvjJMyb/mZfPm2/HWSCTvQPhg3wE=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css" integrity="sha256-uKEg9s9/RiqVVOIWQ8vq0IIqdJTdnxDMok9XhiqnApU=" crossorigin="anonymous" />
</head>

<body>
<div id="content" class="container">
<h1><?php echo picescape(APP_NAME); ?></h1>
<h2>File Browser</h2>

<div class="row">
<div id="paths" class="col-xs-12 col-md-6">
<div class="form-group">
    <label for="paths-select">Paths</label>
    <select id="paths-select" class="form-control">
    <option value=""></option>
    <?php foreach ($paths as $pathID => $pathName): ?>
    <option value="<?php echo $pathID; ?>"><?php echo picescape($pathName); ?></option>
    <?php endforeach; ?>
    </select>
</div>
</div>

<div id="global-toolbar" class="col-xs-12 col-md-6">
    <div class="dropdown hidden-xs hidden-sm">
        <button type="button" id="actions-menu" class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
            <span class="caret"></span>
        </button>
        <div class="dropdown-menu pull-right" role="menu" aria-labelledby="actions-menu">
            <button type="button" data-file-locator-activate class="btn btn-link btn-block">Load Shared File(s)</button>
        </div>
    </div>
    <div class="visible-xs visible-sm">
        <button type="button" id="actions-list" class="btn btn-link" data-toggle="visible-state" data-target="#global-toolbar-mobile" aria-haspopup="true" aria-expanded="false">
            Actions
            <span class="caret"></span>
        </button>
        <ul id="global-toolbar-mobile" class="list-inline" data-visible-state="closed" role="menu" aria-labelledby="actions-list">
            <li><button type="button" data-file-locator-activate class="btn btn-block">Load Shared File</button></li>
        </ul>
    </div>
</div>
</div>
<br>

<div class="row">
<div class="col-xs-12 col-md-11">
<div id="browser-container" class="table-responsive" style="display:none;">

<h4 id="browser-curpath" data-browser-curpath></h4>
<button type="button" data-browser-load-btn class="btn btn-info">Load</button>

<table id="browser" class="table table-striped table-hover">
<thead>
<tr>
    <th style="width: 40px;">&nbsp;</th>
    <th style="width: 35px;">&nbsp;</th>
    <th>Name</th>
    <th>Size</th>
    <th>Last Modified</th>
    <th>&nbsp;</th>
</tr>
</thead>

<tbody data-browser-directories></tbody>
<tbody data-browser-files></tbody>
</table>

</div>
</div>
</div>

</div>

<div id="footer">
<div class="container">
<small>This site runs Pictorials v<?php echo VERSION; ?></small>
</div>
</div>

<div id="loader" style="display:none;">
    <img src="<?php echo assetUrl("img", "spinner.svg"); ?>" alt="Loading" class="loader-img fa-pulse" data-loader-indicator>
    <div class="progress" data-loader-progress style="display:none;">
        <div data-progress-bar class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">&nbsp;</div>
    </div>
</div>

<div class="modal fade" id="files-modal" tabindex="-1" role="dialog" aria-labelledby="files-modal-heading">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="files-modal-heading">Files</h4>
        </div>
        <div class="modal-body">
            <div class="row toolset">
                <div class="col-xs-6">
                    <button type="button" id="btn-modal-download" data-modal-download-btn>Download</button>
                    <button type="button" id="btn-modal-share" data-modal-share-btn>Share</button>
                </div>
                <div class="col-xs-6 text-right">
                    <button type="button" id="btn-rotate-left" data-modal-rotate-btn data-rotate-direction="left">
                        <img src="<?php echo assetUrl("img", "rotate-left.svg"); ?>" alt="Rotate Left" class="rotate-btn-img">
                    </button>
                    <button type="button" id="btn-rotate-right" data-modal-rotate-btn data-rotate-direction="right">
                        <img src="<?php echo assetUrl("img", "rotate-right.svg"); ?>" alt="Rotate Right" class="rotate-btn-img">
                    </button>
                </div>
            </div>
            <div id="files-display" data-modal-carousel></div>
            <div id="files-display-details" class="clearfix" data-modal-image-details></div>
            <div id="files-display-selector" data-modal-carousel-dots></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>
</div>

<div class="modal fade" id="filemetadataeditor-modal" tabindex="-1" role="dialog" aria-labelledby="filemetadataeditor-dialog-heading">
<div class="modal-dialog modal-lg">
    <form class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="filemetadataeditor-dialog-heading" data-form-heading>Metadata</h4>
        </div>
        <div class="modal-body" data-form-container></div>
        <div class="modal-footer">
            <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </form>
</div>
</div>

<div class="modal fade" id="map-modal" tabindex="-1" role="dialog" aria-labelledby="map-dialog-heading">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="map-dialog-heading">Map</h4>
        </div>
        <div class="modal-body">
            <div id="map-container" data-map-container></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>
</div>

<div id="available-actions" style="display: none;">
<div id="available-actions-toolbox" class="sidebar-toolbox xs-hidden force-sm-visible force-md-visible force-lg-visible" role="menu" aria-label="Toolbox">
    <button type="button" class="close xs-visible" aria-label="Close" data-dismiss="toolbox"><span aria-hidden="true">&times;</span></button>
    <ul class="list-unstyled">
    <li><b>Selected:</b> <span data-toolbox-selected-count>0</span></li>
    <li><button type="button" data-event="browser_load_selected_files" data-toolbox-selected-only disabled class="btn btn-info" title="Load selected files">Load</button></li>
    <li><button type="button" data-event="browser_add_selected_files_to_album" data-toolbox-selected-only disabled class="btn btn-info" title="Add selected files to album">Add to Album</button></li>
    <li><button type="button" data-event="browser_share_selected_files" data-toolbox-selected-only disabled class="btn btn-info" title="Share selected files">Share</button></li>
    <li><button type="button" data-event="browser_clear_selected_files" data-toolbox-selected-only disabled class="btn btn-info" title="Clear selected files">Clear</button></li>
    </ul>
</div>
<div class="sidebar-toolbox-toggle xs-visible hidden-sm hidden-md hidden-lg" data-toggle-container>
    <button type="button" class="btn btn-link" data-toggle="toolbox" aria-haspopup="true" aria-expanded="false">Toolbox</button>
</div>
</div>

<div id="keyboard-shortcut-notify" class="sidebar-toolbox hidden-xs" data-toggle="popover" data-placement="left">
Keyboard<br>shortcuts
</div>
<div id="keyboard-shortcut-list">
<ul class="list-unstyled">
    <li><kbd>l</kbd> - display selected images in carousel</li>
    <li><kbd>c</kbd> - clear all selections</li>
    <li><kbd>&rarr;</kbd> - when viewing carousel, move to next image</li>
    <li><kbd>&larr;</kbd> - when viewing carousel, move to previous image</li>
</ul>
</div>

<div style="display:none;">

<script type="application/json" id="ajax-urls">
{
    "filebrowser": "<?php echo scriptUrl("filebrowser"); ?>",
    "fileMetadataFormDownload": "<?php echo scriptUrl("filemetadataeditor", array("action" => "getform")); ?>",
    "fileMetadataUpdate": "<?php echo scriptUrl("filemetadataeditor", array("action" => "update")); ?>",
    "fileMetadataAutocompleteData": "<?php echo scriptUrl("filemetadataeditor", array("action" => "getautocompletedata")); ?>",
    "download": "<?php echo scriptUrl("loadimage"); ?>",
    "downloadFile": "<?php echo scriptUrl("download"); ?>",
    "getalbumdetails": "<?php echo scriptUrl("albumdetails", array("access_mode" => "manage")); ?>",
    "addFileToAlbum": "<?php echo scriptUrl("albumfiles", array("action" => "add", "access_mode" => "manage")); ?>",
    "shareReceive": "<?php echo scriptUrl("share", array("share" => "receive")); ?>",
    "shareSubmit": "<?php echo scriptUrl("share", array("share" => "submit")); ?>",
    "sysload": "<?php echo scriptUrl("sysload"); ?>"
}
</script>

<?php if (isset($mapboxConf)): ?>
<script type="application/json" id="mapbox-config">
<?php echo json_encode($mapboxConf); ?>
</script>
<?php endif; ?>

<script type="application/json" id="image-sizes">
<?php echo json_encode($imageSizes); ?>
</script>

</div>

<div style="display:none;">
<script type="text/x-html-template" id="browser-directory-row-template">
<tr class="dir-row">
    <td>&nbsp;</td>
    <td><img src="<?php echo assetUrl("img", "folder.svg"); ?>" alt="Folder" class="folder-icon"></td>
    <td><a href="#" class="dir" data-relpath="${path}">#{name}</a></td>
    <td colspan="3">&nbsp;</td>
</tr>
</script>

<script type="text/x-html-template" id="browser-file-row-template">
<tr class="file-row" data-relpath="${relpath}">
    <td><input type="checkbox" class="checkbox file-chk"></td>
    <td><img src="<?php echo assetUrl("img", "cross.svg"); ?>" data-relpath="${relpath}" alt="${filename}" class="file-thumb" data-toggle="popover" data-placement="right"></td>
    <td>#{filename}</td>
    <td>#{size}</td>
    <td>#{mtime}</td>
    <td>
        <button type="button" data-file-action="edit-metadata" class="btn btn-link btn-file-action">
            <img src="<?php echo assetUrl("img", "pencil.svg"); ?>" alt="Edit Metadata" title="Edit Metadata">
        </button>
        <button type="button" data-file-action="download" class="btn btn-link btn-file-action">
            <img src="<?php echo assetUrl("img", "download.svg"); ?>" alt="Download" title="Download">
        </button>
    </td>
</tr>
</script>

<script type="text/x-html-template" id="carousel-file-template">
<div class="carousel-file">
    <img src="%{src}" alt="${relpath}" title="${filename}" data-relpath="${relpath}" @{if date_taken}data-date-taken="${date_taken}"@{endif} @{if metadata}data-metadata="${metadata}"@{endif} @{if gps}data-gps="${gps}"@{endif} class="img-responsive img-center">
</div>
</script>

<script type="text/x-html-template" id="carousel-file-details-template">
<div class="date-taken"><b>Date Taken:</b> @{if date_taken}#{date_taken}@{else}unknown@{endif}</div>
@{if metadata}
<div class="metadata-display">
<button type="button" role="button" tabindex="-1" data-metadata-container-trigger data-html="true" data-placement="left" data-trigger="manual">Metadata</button>
<div class="metadata-container" data-metadata-container>%{metadata}</div>
</div>
@{endif}
@{if gps}
<div class="gps-display">
<button type="button" role="button" tabindex="-1" data-map-display-trigger>Map</button>
</div>
@{endif}
</script>

<script type="text/x-html-template" id="file-metadata-list-template">
<ul class="list-unstyled">
@{if exposure}
    <li><b>Exposure time:</b> #{exposure} sec.</li>
@{endif}
@{if iso}
    <li><b>ISO speed:</b> ISO-#{iso}</li>
@{endif}
@{if focal_length}
    <li><b>Focal length:</b> #{focal_length} mm</li>
@{endif}
</ul>
</script>
</div>

<div style="display:none;">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/jquery-ajax-native.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/jquery.shiftcheckbox.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/bootstrap.min.js"); ?>"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.js" integrity="sha256-Wdie7xDu6PuVG6BqNy/dEEYY0jK2JutDYnn0sI19yTw=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.0/pnotify.mobile.js" integrity="sha256-84wtYJTPHtuXdY+6x/khPD5SruMKvYOUsJcYPNJ9dvk=" crossorigin="anonymous"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/bootbox-dev-4.4.1.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "jquery-extensions.js"); ?>"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.js" integrity="sha256-4Cr335oZDYg4Di3OwgUOyqSTri0jUm2+7Gf2kH3zp1I=" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.js" integrity="sha256-GXUdrV9FHGDyzoSGD3O+jR3eYZaZZsjbsMvFhK3C0qg=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.jquery.min.js" integrity="sha256-nORlj0J8ZjvGz+6rtHb2Jcc0QDASsDUNOwUkfcwoW8A=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.min.js" integrity="sha256-tQ3x4V2JW+L0ew/P3v2xzL46XDjEWUExFkCDY0Rflqc=" crossorigin="anonymous"></script>

<script type="text/javascript" src="<?php echo assetUrl("js", "domtools.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "autocomplete-searcher.js"); ?>"></script>

<script type="text/javascript" src="<?php echo assetUrl("js", "clipboard.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "visible-state.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "share-string.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "lazyload.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "key-listener.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "templater.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "modal-manager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "bootbox.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "notification-manager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "toolbox.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "sysload-checker.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "concurrency-manager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "progressive-file-loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "downloader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "paths.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "browser/curpath.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "browser/directories.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "browser/files.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "browser/browser.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-map.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-viewer.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-metadata-editor.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-locator.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "share-manager.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-album-adder.js"); ?>"></script>

<script type="text/javascript" src="<?php echo templateUrl("filebrowser"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-browser.js"); ?>"></script>
</div>

</body>
</html>
