<input type="hidden" name="fileid" value="<?php echo $file->id; ?>">
<input type="hidden" name="filename" value="<?php echo htmlspecialchars($file->filename); ?>">
<div class="grid">
    <div class="file-image">
        <img src="<?php echo assetUrl("img", "cross.svg"); ?>" data-relpath="<?php echo htmlspecialchars($file->filename); ?>" alt="<?php echo htmlspecialchars(basename($file->filename)); ?>">
    </div>
    <div class="file-details">
        <div class="form-group">
            <label for="filemetadataeditor-title" class="control-label">Title</label>
            <input type="text" class="form-control" id="filemetadataeditor-title" name="title" value="<?php echo htmlspecialchars($file->title); ?>">
        </div>
        <div class="form-group">
            <label for="filemetadataeditor-description" class="control-label">Description</label>
            <textarea class="form-control" id="filemetadataeditor-description" name="description" rows="3"><?php echo htmlspecialchars($file->description); ?></textarea>
        </div>
        <div class="form-group">
            <label for="filemetadataeditor-author" class="control-label">Author</label>
            <input type="text" class="form-control" id="filemetadataeditor-author" name="author" value="<?php echo htmlspecialchars($file->author); ?>">
        </div>
        <div class="form-group">
            <label for="filemetadataeditor-location" class="control-label">Location</label>
            <input type="text" class="form-control" id="filemetadataeditor-location" name="location" value="<?php echo htmlspecialchars($file->location); ?>">
        </div>
    </div>
    <div class="file-people">
        People
    </div>
    <div class="file-tags">
        Tags
    </div>
</div>
