<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo APP_NAME; ?> - File Browser</title>
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "bootstrap.min.css"); ?>" media="all">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo assetUrl("css", "styles.css"); ?>" media="all">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.1/leaflet.css" media="all">
</head>

<body>
<div id="content" class="container">
<h1><?php echo APP_NAME; ?></h1>
<h2>File Browser</h2>

<div class="row">
<div id="paths" class="col-xs-12 col-md-6">
<div class="form-group">
    <label for="paths-select">Albums</label>
    <select id="paths-select" class="form-control">
    <option value=""></option>
    <?php foreach ($paths as $pathID => $path): ?>
    <option value="<?php echo $pathID; ?>"><?php echo $path["name"]; ?></option>
    <?php endforeach; ?>
    </select>
</div>
</div>
</div>
<br>

<div id="browser-container" class="table-responsive" style="display:none;">
<h4 id="browser-curpath" data-browser-curpath></h4>
<button type="button" data-browser-load-btn class="btn btn-info">Load</button>

<table id="browser" class="table table-striped table-hover">
<thead>
<tr>
    <th style="width: 40px;">&nbsp;</th>
    <th style="width: 35px;">&nbsp;</th>
    <th>Name</th>
    <th>Size</th>
    <th>Last Modified</th>
    <th>&nbsp;</th>
</tr>
</thead>

<tbody data-browser-directories></tbody>
<tbody data-browser-files></tbody>
</table>

</div>

</div>

<div id="footer">
<div class="container">
<small>This site runs Pictorials v<?php echo VERSION; ?></small>
</div>
</div>

<div id="loader" style="display:none;">
    <img src="<?php echo assetUrl("img", "spinner.svg"); ?>" alt="Loading" class="loader-img fa-pulse" data-loader-indicator>
    <div class="progress" data-loader-progress style="display:none;">
        <div data-progress-bar class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">&nbsp;</div>
    </div>
</div>

<div class="modal fade" id="files-modal" tabindex="-1" role="dialog" aria-labelledby="files-modal-heading">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="files-modal-heading">Files</h4>
        </div>
        <div class="modal-body">
            <div class="row toolset">
                <div class="col-xs-6">
                    <button type="button" id="btn-modal-download" data-modal-download-btn>Download</button>
                </div>
                <div class="col-xs-6 text-right">
                    <button type="button" id="btn-rotate-left" data-modal-rotate-btn data-rotate-direction="left">
                        <img src="<?php echo assetUrl("img", "rotate-left.svg"); ?>" alt="Rotate Left" class="rotate-btn-img">
                    </button>
                    <button type="button" id="btn-rotate-right" data-modal-rotate-btn data-rotate-direction="right">
                        <img src="<?php echo assetUrl("img", "rotate-right.svg"); ?>" alt="Rotate Right" class="rotate-btn-img">
                    </button>
                </div>
            </div>
            <div id="files-display" data-modal-carousel></div>
            <div id="files-display-details" data-modal-image-details></div>
            <div id="files-display-selector" data-modal-carousel-dots></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>
</div>

<div id="keyboard-shortcut-notify" class="hidden-xs" data-toggle="popover" data-placement="left">
Keyboard<br>shortcuts
</div>
<div id="keyboard-shortcut-list">
<ul class="list-unstyled">
    <li><kbd>l</kbd> - display selected images in carousel</li>
    <li><kbd>c</kbd> - clear all selections</li>
    <li><kbd>&rarr;</kbd> - when viewing carousel, move to next image</li>
    <li><kbd>&larr;</kbd> - when viewing carousel, move to previous image</li>
</ul>
</div>

<script type="application/json" id="ajax-urls">
{
    "filebrowser": "<?php echo scriptUrl("filebrowser"); ?>",
    "download": "<?php echo scriptUrl("loadimage"); ?>",
    "downloadFile": "<?php echo scriptUrl("download"); ?>",
    "sysload": "<?php echo scriptUrl("sysload"); ?>"
}
</script>

<script type="application/json" id="image-sizes">
<?php echo json_encode($imageSizes); ?>
</script>

<div style="display:none;">
<script type="text/x-html-template" id="browser-directory-row-template">
<tr class="dir-row">
    <td>&nbsp;</td>
    <td><img src="<?php echo assetUrl("img", "folder.svg"); ?>" alt="Folder" class="folder-icon"></td>
    <td><a href="#" class="dir" data-relpath="${path}">#{name}</a></td>
    <td colspan="3">&nbsp;</td>
</tr>
</script>

<script type="text/x-html-template" id="browser-file-row-template">
<tr class="file-row" data-relpath="${relpath}">
    <td><input type="checkbox" class="checkbox file-chk"></td>
    <td><img src="<?php echo assetUrl("img", "cross.svg"); ?>" data-relpath="${relpath}" alt="${filename}" class="file-thumb" data-toggle="popover" data-placement="right"></td>
    <td>#{filename}</td>
    <td>#{size}</td>
    <td>#{mtime}</td>
    <td><a href="#" class="file-download">Download</a></td>
</tr>
</script>

<script type="text/x-html-template" id="carousel-file-template">
<div class="carousel-file">
    <img src="%{src}" alt="${relpath}" title="${filename}" data-relpath="${relpath}" data-date-taken="${date_taken}" data-metadata="${metadata}" class="img-responsive img-center">
</div>
</script>
</div>

<div style="display:none;">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/jquery-ajax-native.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/jquery.shiftcheckbox.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "vendor/bootstrap.min.js"); ?>"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.1/leaflet.js"></script>

<script type="text/javascript" src="<?php echo assetUrl("js", "lazyload.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "key-listener.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "templater.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "cancellable-file-loader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "downloader.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "paths.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "browser.js"); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-viewer.js"); ?>"></script>
<script type="text/javascript" src="<?php echo templateUrl(""); ?>"></script>
<script type="text/javascript" src="<?php echo assetUrl("js", "file-browser.js"); ?>"></script>
</div>

</body>
</html>
